FROM apache/airflow:2.8.0

# Usamos directamente el usuario airflow (NO root)
USER airflow

# Instalamos el provider de Spark con pip como usuario airflow
RUN pip install --no-cache-dir apache-airflow-providers-apache-spark

USER root

RUN apt-get update \
    && apt-get install -y openjdk-17-jdk-headless \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="$JAVA_HOME/bin:$PATH"

USER airflow
