# Configuración de Spark para integración con Hive
spark.sql.warehouse.dir=/spark-warehouse
spark.hadoop.hive.metastore.uris=thrift://hive:9083
spark.sql.catalogImplementation=hive
spark.sql.hive.metastore.version=2.3.9
spark.sql.hive.metastore.jars=builtin
spark.sql.hive.metastore.sharedPrefixes=org.postgresql

# Configuración de memoria
spark.driver.memory=1g
spark.executor.memory=1g

# Configuración de logs
spark.eventLog.enabled=true
spark.eventLog.dir=/tmp/spark-events
